import { Footer } from "@/components/footer/footer";
import { Header } from "@/components/header/header";
import { Box, Button, Input, Text } from "@chakra-ui/react";
import { NextPage } from "next";
import Head from "next/head";
import LoginForm from "@/components/forms/loginForm";

const LoginPage: NextPage = () => {
    return (
        <>
        <Head>
            <title>Motors Shop</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* <Box display={"flex"} flexDir={"column"} justifyContent={"center"} minW={"20rem"}> */}
            <Header />
        {/* </Box> */}
        <LoginForm/>
        <Footer />
        </>
    )
}

export default LoginPage